### ISSUE TITLE
Amazing solution, would recommend, but no license

### ISSUE THREAD

**Issue by kobrien603** [VictorBezak/Plotly_Multi-Axes_Gridlines#1]
Could you please add a license, or specify how to credit your work. The solution looks promising but at the moment can't be used based on GitHub "No License" guidelines.

**Comment by VictorBezak** [comment]
I appreciate the notice and recommendation! I've updated the repo to
include a MIT license. Admittedly, I'm relatively new to software and this
is the first time I've made an effort to make something for the
community--I completely overlooked the licensing. If you've got any
questions at all, please do let me know.

All the best!
Victor
