### ISSUE TITLE
Python Class 

### ISSUE THREAD

**Issue by MZH-bust** [VictorBezak/Plotly_Multi-Axes_Gridlines#2]
Hi Victor,
thank you so much for this. 
Based on your guide i have built a Python class. 
Perhaps that will help some other guys out there as a starting point. 

[y_axis_align_gridlines.txt](https://github.com/VictorBezak/Plotly_Multi-Axes_Gridlines/files/4344064/y_axis_align_gridlines.txt)

**Comment by VictorBezak** [comment]
You're very welcome, I'm glad to see you make the logic more accessible for others!

I recently pushed a small update to account for axes that have ranges of less than 1.0

Please do let me know if you have any questions or feedback. Happy coding!

**Comment by pkozul** [comment]
Victor, thanks for the enhancement to cater for axes with ranges < 1. This now works great and has fixed all the charts in the app I am building. Fantastic effort!
